In [23]:
import seaborn as sns
import missingno as msno
df = sns.load_dataset('titanic')
df = df.select_dtypes(include = ['float64', 'int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

**bu bölümdekiler ileride daha iyi kavranacak kavramlardır.
Makine öğrenmesi yöntemi ile eksik değerlere tahmini degerler atayacagız**

In [24]:
pip install ycimpute==0.1.1

Note: you may need to restart the kernel to use updated packages.


In [25]:
from ycimpute.imputer import knnimput

In [26]:
#veri setini numpy arrayine çeviricez çümkü knnimput bizden bir numpy array bekliyor
#doalyısıyla öne numpy arrayine donusturup veriyi saklıcaz ve sonra tekrar atama yapacagız 
var_names=list(df)
#list(df)=bize columns'u verir denendi, Bu işlmi df nin ismleini bir yerde saklmak için yaptık
import numpy as np
n_df=np.array(df)
# numpy array yaptıgımız n_df imizi görüntüleelim
n_df[0:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [27]:
#dff isimli yeni bir nesne oluşturalım bunun için knnimput fonksiyonunu kullanalım

In [28]:
dff=knnimput.KNN(k=4).complete(n_df)
#k burada komşuluk sayısını ifade eder
#bu kısımlar zaten makine öğrenmesi bölümünde detaylıca işlenecek. şimdilik hızlıca geçelim.

Imputing row 1/891 with 0 missing, elapsed time: 0.117
Imputing row 101/891 with 0 missing, elapsed time: 0.118
Imputing row 201/891 with 0 missing, elapsed time: 0.119
Imputing row 301/891 with 1 missing, elapsed time: 0.120
Imputing row 401/891 with 0 missing, elapsed time: 0.121
Imputing row 501/891 with 0 missing, elapsed time: 0.123
Imputing row 601/891 with 0 missing, elapsed time: 0.124
Imputing row 701/891 with 0 missing, elapsed time: 0.125
Imputing row 801/891 with 0 missing, elapsed time: 0.126


In [29]:
dff # dff= bir numpy array'idir ve bir pandas array'ine çevirmeliyiz

array([[ 0.        ,  3.        , 22.        ,  1.        ,  0.        ,
         7.25      ],
       [ 1.        ,  1.        , 38.        ,  1.        ,  0.        ,
        71.2833    ],
       [ 1.        ,  3.        , 26.        ,  0.        ,  0.        ,
         7.925     ],
       ...,
       [ 0.        ,  3.        , 22.46902398,  1.        ,  2.        ,
        23.45      ],
       [ 1.        ,  1.        , 26.        ,  0.        ,  0.        ,
        30.        ],
       [ 0.        ,  3.        , 32.        ,  0.        ,  0.        ,
         7.75      ]])

In [30]:
import pandas as pd
dff=pd.DataFrame(dff,columns=var_names)
dff

survived  pclass        age  sibsp  parch     fare
0         0.0     3.0  22.000000    1.0    0.0   7.2500
1         1.0     1.0  38.000000    1.0    0.0  71.2833
2         1.0     3.0  26.000000    0.0    0.0   7.9250
3         1.0     1.0  35.000000    1.0    0.0  53.1000
4         0.0     3.0  35.000000    0.0    0.0   8.0500
..        ...     ...        ...    ...    ...      ...
886       0.0     2.0  27.000000    0.0    0.0  13.0000
887       1.0     1.0  19.000000    0.0    0.0  30.0000
888       0.0     3.0  22.469024    1.0    2.0  23.4500
889       1.0     1.0  26.000000    0.0    0.0  30.0000
890       0.0     3.0  32.000000    0.0    0.0   7.7500

[891 rows x 6 columns]

In [32]:
#simdi eksik degerleri tekrar kontrol edelim
dff.isnull().sum()
#görüldüğü üzre eksik degerler doldu.
#burda kullanılan knn algoritması makine ögrenmesi şeysi

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64

şimdi bu işlemi **Random Forest** algoritması ile yapalım

In [41]:
import seaborn as sns
import missingno as msno
df = sns.load_dataset('titanic')
df = df.select_dtypes(include = ['float64', 'int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [45]:
#veri setini numpy arrayine çeviricez çümkü knnimput bizden bir numpy array bekliyor
#doalyısıyla öne numpy arrayine donusturup veriyi saklıcaz ve sonra tekrar atama yapacagız 
var_names=list(df)
#list(df)=bize columns'u verir denendi, Bu işlmi df nin ismleini bir yerde saklmak için yaptık
import numpy as np
n_df=np.array(df)
# numpy array yaptıgımız n_df imizi görüntüleelim
n_df[0:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [46]:
from ycimpute.imputer import iterforest
dff=iterforest.IterImput().complete(n_df)
dff

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    , 26.52  ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [47]:
import pandas as pd
# eger dff=pd.DataFrame(dff,columns=var_names) şeklinde yapıp columsları belirtmezsek 
#aşagıdaki gibi 1,2,3,4 seklinde sütun ismi verir 

dff=pd.DataFrame(dff)
dff

0    1      2    3    4        5
0    0.0  3.0  22.00  1.0  0.0   7.2500
1    1.0  1.0  38.00  1.0  0.0  71.2833
2    1.0  3.0  26.00  0.0  0.0   7.9250
3    1.0  1.0  35.00  1.0  0.0  53.1000
4    0.0  3.0  35.00  0.0  0.0   8.0500
..   ...  ...    ...  ...  ...      ...
886  0.0  2.0  27.00  0.0  0.0  13.0000
887  1.0  1.0  19.00  0.0  0.0  30.0000
888  0.0  3.0  26.52  1.0  2.0  23.4500
889  1.0  1.0  26.00  0.0  0.0  30.0000
890  0.0  3.0  32.00  0.0  0.0   7.7500

[891 rows x 6 columns]

şimdi bu işlemi **EM** algoritması ile yapalım

In [48]:
import seaborn as sns
import missingno as msno
df = sns.load_dataset('titanic')
df = df.select_dtypes(include = ['float64', 'int64'])
print(df.head())
df.isnull().sum()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500


survived      0
pclass        0
age         177
sibsp         0
parch         0
fare          0
dtype: int64

In [49]:
#veri setini numpy arrayine çeviricez çümkü knnimput bizden bir numpy array bekliyor
#doalyısıyla öne numpy arrayine donusturup veriyi saklıcaz ve sonra tekrar atama yapacagız 
var_names=list(df)
#list(df)=bize columns'u verir denendi, Bu işlmi df nin ismleini bir yerde saklmak için yaptık
import numpy as np
n_df=np.array(df)
# numpy array yaptıgımız n_df imizi görüntüleelim
n_df[0:10]

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ],
       [ 0.    ,  3.    ,     nan,  0.    ,  0.    ,  8.4583],
       [ 0.    ,  1.    , 54.    ,  0.    ,  0.    , 51.8625],
       [ 0.    ,  3.    ,  2.    ,  3.    ,  1.    , 21.075 ],
       [ 1.    ,  3.    , 27.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  2.    , 14.    ,  1.    ,  0.    , 30.0708]])

In [51]:
from ycimpute.imputer import EM
dff=EM().complete(n_df)
dff

array([[ 0.        ,  3.        , 22.        ,  1.        ,  0.        ,
         7.25      ],
       [ 1.        ,  1.        , 38.        ,  1.        ,  0.        ,
        71.2833    ],
       [ 1.        ,  3.        , 26.        ,  0.        ,  0.        ,
         7.925     ],
       ...,
       [ 0.        ,  3.        , 23.30151219,  1.        ,  2.        ,
        23.45      ],
       [ 1.        ,  1.        , 26.        ,  0.        ,  0.        ,
        30.        ],
       [ 0.        ,  3.        , 32.        ,  0.        ,  0.        ,
         7.75      ]])

In [57]:
dff=pd.DataFrame(dff,columns=var_names)
dff

survived  pclass        age  sibsp  parch     fare
0         0.0     3.0  22.000000    1.0    0.0   7.2500
1         1.0     1.0  38.000000    1.0    0.0  71.2833
2         1.0     3.0  26.000000    0.0    0.0   7.9250
3         1.0     1.0  35.000000    1.0    0.0  53.1000
4         0.0     3.0  35.000000    0.0    0.0   8.0500
..        ...     ...        ...    ...    ...      ...
886       0.0     2.0  27.000000    0.0    0.0  13.0000
887       1.0     1.0  19.000000    0.0    0.0  30.0000
888       0.0     3.0  23.301512    1.0    2.0  23.4500
889       1.0     1.0  26.000000    0.0    0.0  30.0000
890       0.0     3.0  32.000000    0.0    0.0   7.7500

[891 rows x 6 columns]

In [59]:
dff.isnull().sum()

survived    0
pclass      0
age         0
sibsp       0
parch       0
fare        0
dtype: int64