* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı 
* dtype: array veri tipi

In [23]:
#TEK BOYUTLU
import numpy as np
a=np.random.randint(10,size=10)
a


array([0, 6, 8, 9, 9, 0, 1, 1, 8, 0])

In [11]:
a.ndim

1

In [12]:
a.shape


(10,)

In [13]:
a.size

10

In [14]:
a.dtype

dtype('int32')

In [17]:
#TEK BOYUTLU VE CİFT BOYUTLU ARASINDA FARK YOK AMA YİNEDE CİFT BOYUTUDA YAPALIM.
import numpy as np
a=np.random.randint(10,size=(3,5))
a

array([[2, 4, 1, 1, 8],
       [0, 9, 3, 8, 8],
       [8, 7, 2, 5, 8]])

In [18]:
a.ndim

2

In [19]:
a.shape


(3, 5)

In [20]:
a.size

15

In [21]:
a.dtype

dtype('int32')

In [30]:

#aşağıdaki kodlar öylesine bağımsız denemeler...
np.random.randint(0,20,(3,3,2))

array([[[ 3,  0],
        [18,  2],
        [ 2,  0]],

       [[12, 16],
        [14,  8],
        [18, 14]],

       [[17,  0],
        [ 9, 13],
        [ 9,  0]]])

In [31]:
5*np.array([1, 2,3])

array([ 5, 10, 15])