In [15]:
import numpy as np

a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#kac boyutlu?
a.ndim

1

In [19]:
a
#dikkat tek parantez 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b=a.reshape(1,9)
#Burada çift köşeli parantez çünkü çok boyutlu array
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
a.ndim


1

In [24]:
b.ndim

2