In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [8]:
#concatenate=birleşmek,sıralamk anlamına gelir
birlesikArray=np.concatenate([x,y])
birlesikArray

array([1, 2, 3, 4, 5, 6])

In [11]:
#2 boyutta birleştirme
a=np.array([[1,2,3],
            [4,5,6]])
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
#eger alta degil, sagına falan eklemek istersek, 
#axis= eksen icin kullanılır 
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [13]:
#varsayılan değer 0 oldugundan alta yerleştirir
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])