In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,99,99,3,2,1])
np.split(x,[3,5])
#x i split et, 3'ten 5'e kadar bir böl dedik. 

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x,[3,5])
a

array([1, 2, 3])

In [5]:
b

array([99, 99])

In [6]:
c

array([3, 2, 1])

In [14]:
#iki boyutlu array oluşturma
m=np.arange(0,16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
#şimdi bu listeyi, 2. satırdan bölüp yanına ekleyelim.
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
ust,alt=np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
#birleştirmek için ise bir önceki ders 
#kullandığımız fonksiyonu kullanacağız.\|/ concatenate.
np.concatenate([alt,ust],axis=1)

array([[ 8,  9, 10, 11,  0,  1,  2,  3],
       [12, 13, 14, 15,  4,  5,  6,  7]])

In [30]:
## sütunları bölmek için ise;
sağdik,soldik=np.hsplit(m,[2])
np.concatenate([sağdik,soldik])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [31]:
np.concatenate([sağdik,soldik],axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])