In [1]:
import numpy as np

In [9]:
v= np.array([2.1,4,3,5])
v

array([2.1, 4. , 3. , 5. ])

In [10]:
np.sort(v)

array([2.1, 3. , 4. , 5. ])

In [11]:
v
#dikkat et, veri aslında değişmedi. alttaki çıktı sırasız 

array([2.1, 4. , 3. , 5. ])

In [12]:
#ama pythonun sortu kullansaydık,
v.sort()
v

array([2.1, 3. , 4. , 5. ])

In [13]:
v

array([2.1, 3. , 4. , 5. ])

In [14]:
#veri ilelebet değişecekti

In [15]:
#iki boyutlu array sıralama
m= np.random.normal(20,5,(3,3))
m

array([[22.60338216, 15.60525153, 12.77779576],
       [15.04303034, 18.97549734, 20.12279722],
       [16.70815976, 25.53901151, 18.90531546]])

In [23]:
np.sort(m,axis=1)
#satırları sıralar

array([[12.77779576, 15.60525153, 22.60338216],
       [15.04303034, 18.97549734, 20.12279722],
       [16.70815976, 18.90531546, 25.53901151]])

In [24]:
np.sort(m,axis=0)
#sütunları sıralar

array([[15.04303034, 15.60525153, 12.77779576],
       [16.70815976, 18.97549734, 18.90531546],
       [22.60338216, 25.53901151, 20.12279722]])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])