In [1]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
 [v[0],v[1],v[2]]

[0, 3, 6]

In [3]:
al_getir=[1,2,5,6]
v[al_getir]

array([ 3,  6, 15, 18])

In [5]:
#2boyutta fancy
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
satir=np.array([1,3])
sütun=np.array([1,2])
m[satir,sütun]
#1. satir1 1. sütun ve 3. satir 2. sütun. 

array([ 5, 14])

In [7]:
satir

array([1, 3])

In [8]:
sütun

array([1, 2])

In [9]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
#basit indeks ile fancy indeks
m[0:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [11]:
 v[[1,2]]

array([3, 6])

In [12]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])