In [5]:
import numpy as np
v=np.array([1,2,3,4,5,6,7])
v<4

array([ True,  True,  True, False, False, False, False])

In [6]:
#burada bir önceki derste öğrendigimiz fancy'i kullanırsar 
#degerlere erişebiliriz
v[v<3]

array([1, 2])

In [7]:
v*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [8]:
v


array([1, 2, 3, 4, 5, 6, 7])

In [9]:
v[v<3]*5

array([ 5, 10])