In [3]:
import numpy as np
v=np.array([1,2,3,4,5])
v*5

array([ 5, 10, 15, 20, 25])

In [4]:
v*2

array([ 2,  4,  6,  8, 10])

In [5]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [9]:
(v**2)[4]

25

In [10]:
#bu işemler ufuct ile yapılır. yyani,
#v*2 dediğimizde, np.multiply(v,2) çalışır 
#v+10 dediğimizde, np.add(v,10)çalışır
#bu çalışma s,steminin bilinmesi faydalıdır

In [11]:
v%3

array([1, 2, 0, 1, 2], dtype=int32)

In [13]:
#mutlak deger alma
mutlakdeneme=np.array([1,2,3,-4,-5])
np.absolute(mutlakdeneme)

array([1, 2, 3, 4, 5])

In [15]:
np.sin(360)

0.9589157234143065

In [18]:
np.tan(45)

1.6197751905438615

In [20]:
np.tan(23)

1.5881530833912738

In [22]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [25]:
np.tan(v)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])