In [1]:
import numpy as np

In [7]:
np_arr=np.random.normal(3,3,(3,3))
np_arr

array([[-0.64472165,  6.43501457,  0.52676246],
       [ 2.48524329,  3.58212921, -1.59157869],
       [ 1.86911129,  5.49094006,  3.61983614]])

In [9]:
np_arr.shape

(3, 3)

In [10]:
np.ndim

<function numpy.ndim(a)>

In [36]:
x=np.random.randint(5,10,size=(4,3))
x

array([[9, 8, 6],
       [5, 9, 9],
       [9, 9, 5],
       [9, 9, 7]])

In [41]:
x=x.reshape(2,6)
x

array([[9, 8, 6, 5, 9, 9],
       [9, 9, 5, 9, 9, 7]])

In [42]:
x.T

array([[9, 9],
       [8, 9],
       [6, 5],
       [5, 9],
       [9, 9],
       [9, 7]])

In [43]:
?np.hsplit

Signature: np.hsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
>>> np.hsplit(x, np.array([3, 6]))
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([], shape=(4, 0), dtyp

In [44]:
np.hsplit(x,[2])

[array([[9, 8],
        [9, 9]]),
 array([[6, 5, 9, 9],
        [5, 9, 9, 7]])]

In [50]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [51]:
a[:,]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
a[:,2]

array([ 2,  7, 12, 17])

In [59]:
a[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]])

In [60]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
a[1,2,3]

IndexError: too many indices for array

In [37]:
import pandas as pd 
import numpy as np

dizi=np.random.randint(10,15,size=(3,3))
dizi

import numpy as np
dizi = np.arange(1,10).reshape((3,3))
dizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
dizi=pd.DataFrame(dizi)
dizi

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [39]:
pd.DataFrame(dizi,columns=["sd","kd","ld"])

sd  kd  ld
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN

In [40]:
dizi

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [63]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [64]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [65]:
sozluk

{'var1': array([6, 3, 6, 8, 6]),
 'var2': array([5, 1, 3, 8, 0]),
 'var3': array([3, 8, 1, 9, 9])}

In [66]:
df=pd.DataFrame(sozluk)

In [67]:
df

var1  var2  var3
0     6     5     3
1     3     1     8
2     6     3     1
3     8     8     9
4     6     0     9

In [69]:
a=np.array([4,5,6,7,8])
pd.DataFrame(a,columns=["deg1"])

deg1
0     4
1     5
2     6
3     7
4     8

In [70]:
df

var1  var2  var3
0     6     5     3
1     3     1     8
2     6     3     1
3     8     8     9
4     6     0     9

In [78]:
df.drop(0)

var1  var2  var3
2     6     3     1
3     8     8     9
4     6     0     9

In [80]:
#df.drop(1,inplace=True)
#ile 1'i KALICI OLARAK sildik. 

In [82]:
df.drop("var2",axis=1)

var1  var3
0     6     3
2     6     1
3     8     9
4     6     9

In [83]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    19     6     6
1    29    16    29
2    21     3    24
3    17     9     3
4    20    27     5
5    22    19    27
6    16     1    23
7     2    18    29
8    11    21    21
9     9    25     8

In [84]:
df.loc[0:4]

var1  var2  var3
0    19     6     6
1    29    16    29
2    21     3    24
3    17     9     3
4    20    27     5

In [85]:
df.loc[2:3]

var1  var2  var3
2    21     3    24
3    17     9     3

In [86]:
df.iloc[0:2]

var1  var2  var3
0    19     6     6
1    29    16    29

In [90]:
df.iloc[0:4,1:3]

var2  var3
0     6     6
1    16    29
2     3    24
3     9     3