In [9]:
# İKİ BİLİNMEYENLİ DEKLEM ÇÖZELİM.
import numpy as np 
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [7]:
a

array([[5, 1],
       [1, 3]])

In [8]:
b

array([12, 10])

In [10]:
#aşagıdaki modül,numpy da lineer cebir işlemleri için özelleşmiş 
#alt paket içerisinden çaırılan solve isimli alt pakettir
#dedikki birinci argüman ve 2. argüman arası ilişki neticesinde
#oluşacak katsayıları hesapla

x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])