In [40]:
import random 
import numpy as np
dizi=[[10*random.random() for i in range(5)] for j in range(3) ]
dizi

[[6.808484472303762,
  8.313254516801548,
  0.021456482921291542,
  1.8765560073279541,
  4.562144053660352],
 [4.934347624016102,
  0.38455386653504897,
  3.2229077473784473,
  5.160102889282381,
  1.6788062981828877],
 [6.263072448257826,
  1.935349823895145,
  7.387156572150766,
  6.899777968274011,
  2.3072764922665767]]

In [41]:
dizi[0][1]

8.313254516801548

In [42]:
#ortalaması 10 standart sapması 5 olan [2][3]' lük bir diz;
numpy.random.normal(10,5,(2,3))

array([[ 5.71583401,  6.52687313,  0.10219437],
       [11.50258297,  5.06069607,  5.28936302]])

In [77]:
#ortalaması 5, standart sapması 5 olan [2][3]' lük bir diz;
c=3;
v=4
arry=numpy.random.random_integers(20,size=(c,v))
arry

C:\Users\bedir\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(1, 20 + 1) instead
  after removing the cwd from sys.path.


array([[ 4, 14, 10,  7],
       [ 2,  2, 10, 14],
       [17,  1,  1, 15]])

In [85]:
for i in range(c):
    print(i)

0
1
2


In [83]:
len(arry[2])

4

In [89]:
for i in range(1,5):
    print(i)

1
2
3
4


In [90]:
i=5
if True:
    i=10
i

10

In [96]:
import numpy as np
np.array
class PeakFinder2D:
    def __init__(self,nrow,ncol):
        self.nrow=nrow
        self.ncol=ncol
        #ortalaması 5, standart sapması 5 olan [nrow][ncol]' lük bir diz;
        #self.arry=np.random.random_integers(20,size=(self.nrow,self.ncol))
        self.arry=np.array([[4,6,3,11,9],[2,7,20,14,11],[11,8,13,10,3],[7,9,4,19,8]])
        print(self.arry)

    def greedyAlg(self):
        peak=self.arry[0][0]
        for i in range(self.nrow-2):
            for j in range(self.ncol-2):
                if self.arry[i][j]<self.arry[i+1][j]:
                    i=i+1
                if self.arry[i][j]>=self.arry[i+1][j] and self.arry[i][j]>=self.arry[i][j+1]:
                    peak=self.arry[i][j]
                    return peak

    def findMaxOnCol(col):
        imax = 0
        for i in range(self,col):
            if(self.arry[i][col]>self.arry[imax][col]):
                imax = i    
        return imax
    
    def findMaxOnRow(self,row):
        imax=int()
        for i in range(1,row):
            print(i,imax)
            if(self.arry[row][i]>self.arry[row][i+1]):
                imax = i

        return imax

In [97]:
PeakFinder2D1=PeakFinder2D(5,6)
maxonrow=PeakFinder2D1.findMaxOnRow(1)
print("\nMaxOnRow=",maxonrow)

[[ 4  6  3 11  9]
 [ 2  7 20 14 11]
 [11  8 13 10  3]
 [ 7  9  4 19  8]]

MaxOnRow= 0


In [120]:
class PeakFinder2D:
    def __init__(self,nrow,ncol,count=1):
        self.nrow=nrow
    def fonks(self, say=0):
        if say<5:
            print(say)
            return self.fonks(say++1)

In [121]:
peak=PeakFinder2D(2,3)

In [123]:
peak.fonks(3)

3
4


In [104]:
print(peak.nrow)

2


In [130]:
arry=np.array([[4,6,3,11,9,9,6,3,11],[2,7,6,3,11,20,14,11,7],[11,12,5,4,3,13,15,16,17],
                            [7,9,4,19,8,88,6,3,11],[5,6,3,11,20,30,19,8,5],[0,40,6,3,11,0,19,8,5],
                            [5,4,3,197,8,5,6,3,11],[2,90,30,6,3,11,19,8,5],[40,40,195,8,19,8,5,5,7],[40,40,195,8,19,8,5,5,7]])

In [131]:
arry

array([[  4,   6,   3,  11,   9,   9,   6,   3,  11],
       [  2,   7,   6,   3,  11,  20,  14,  11,   7],
       [ 11,  12,   5,   4,   3,  13,  15,  16,  17],
       [  7,   9,   4,  19,   8,  88,   6,   3,  11],
       [  5,   6,   3,  11,  20,  30,  19,   8,   5],
       [  0,  40,   6,   3,  11,   0,  19,   8,   5],
       [  5,   4,   3, 197,   8,   5,   6,   3,  11],
       [  2,  90,  30,   6,   3,  11,  19,   8,   5],
       [ 40,  40, 195,   8,  19,   8,   5,   5,   7],
       [ 40,  40, 195,   8,  19,   8,   5,   5,   7]])

In [136]:
len(arry[0])

9